# Generated by Django 3.1.4 on 2020-12-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0007_auto_20201229_2040'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
