# Generated by Django 3.1.4 on 2020-12-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumb',
            field=models.ImageField(default='default.png', null=True, upload_to=''),
        ),
    ]
