# Generated by Django 3.1.4 on 2020-12-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0002_product_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product',
            new_name='price',
        ),
    ]
