# Generated by Django 3.1.4 on 2021-01-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0009_auto_20210101_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
