# Generated by Django 3.1.4 on 2021-01-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0011_auto_20210101_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='istore.product'),
        ),
    ]
