# Generated by Django 3.1.4 on 2021-01-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0014_auto_20210102_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='istore.OrderItem'),
        ),
    ]
