# Generated by Django 3.1.4 on 2021-01-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0016_orderitem_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
