# Generated by Django 3.1.4 on 2021-01-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0018_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='istore.OrderItem'),
        ),
    ]
