# Generated by Django 3.1.4 on 2021-01-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0019_auto_20210102_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
