# Generated by Django 3.1.4 on 2021-01-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0020_auto_20210102_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
