# Generated by Django 3.1.4 on 2021-01-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0022_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
