# Generated by Django 3.1.4 on 2021-01-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0025_auto_20210105_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=100),
        ),
    ]
