# Generated by Django 3.1.4 on 2021-01-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0026_auto_20210105_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
