# Generated by Django 3.1.4 on 2021-01-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0027_auto_20210105_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
