# Generated by Django 3.1.4 on 2021-01-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0028_auto_20210105_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=100),
        ),
    ]
