# Generated by Django 3.1.3 on 2021-01-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0029_auto_20210105_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
