# Generated by Django 3.2.4 on 2022-01-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0032_auto_20210106_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='zip',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
