# Generated by Django 3.2.4 on 2022-01-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0033_auto_20220110_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ref',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
