# Generated by Django 3.2.4 on 2022-01-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0034_orderitem_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ref',
        ),
    ]
